### ISSUE TITLE
TREC2016 RTS Evaluation Metric: Treatment of latency penalty 

### ISSUE THREAD

**Issue by LuchenTan** [trecrts/trecrts.github.io#8]
We are discussing another important aspect of evaluation metrics here, the delay penalty. In TREC2015 Microblog Track, a latency penalty was applied to the gain of each tweet. The maximum acceptable delay was 100 minutes after the tweet was posted. A linear decay was computed as MAX(0, (100-delay)/100). 

In the arXiv paper showing below, our group in UWaterloo studies the effect of delay penalties. 

http://arxiv.org/abs/1606.03066

We removed delay penalty from the evaluation metric first. Surprisingly, the scores of most systems stayed the same, which means these systems made immediate decisions with respect to the incoming tweets. 

Recall that in the evaluation protocol, tweets are semantically clustered into “equivalence sets” that contain substantively the same information. Adopted idea from Temporal Summarization Track, it seems appropriate to compute the latency penalty with respect to the first tweet in each cluster. We also plotted the difference of scores between wrt the first tweet in each cluster and wrt the posted tweet. 

We propose one of the following solutions for this year:
1. compute the latency wrt the first tweet in cluster.
2. remove latency penalty from the evaluation metric, but report it separately, e.g., we can plot system effectiveness on a scatterplot.

We are looking for comments, suggestions, etc.

**Comment by telsayed** [comment]
- I think we should keep the penalty to distinguish responsive from non-responsive systems. So, I support option #1, however this assumes that all systems will get this first relevant tweet of the cluster in their streams (which might not be the case due to connection issues).
- Will the penalty be computed similar to last year (i.e., linear decay with max of 100 minutes) but wrt first tweet of cluster?

**Comment by LuchenTan** [comment]
We are suggesting to report latency separately this year. Last year, the 100 mins is a arbitrary number, since we don't have meaningful number yet, we won't add it to the major metric this year.  

And yes, there's change that systems can't recieve the particular first tweet in the cluster, but standing from users' point, users will not know that.

**Comment by lintool** [comment]
Hi @telsayed, details are at: http://trecrts.github.io/TREC2016-RTS-guidelines.html

It is our intention _not_ to have a latency penalty in the gain explicitly, because as @LuchenTan said, the 100 minutes delay threshold from last time was totally arbitrary.

Instead, we want to report the average latency separately - this way, we can plot gain and latency in a scatterplot and see how teams make different tradeoffs (the same we separately reported precision and recall for TTG in 2014). The side benefit of this is that scenario B runs now become comparable to scenario A runs.

Thoughts?

**Comment by KaranSabhnani** [comment]
Based on the discussion above and the analysis done by the organizers, reporting latency separately makes more sense to me because, 1) we don't have a user study that captures users preferences in terms of acceptable latency and 2) now that the latency is computed wrt to the first tweet in the cluster, it is even more difficult and risky to come up with an arbitrary threshold. Moreover I agree that a scatterplot of gain vs. latency  will help us better understand system components/algorithms and tradeoffs.

**Comment by LuchenTan** [comment]
Thanks for your comments, @KarenSabhnani. Yes, we definitely need a user study to learn the user preferences. Maybe later our group or other researchers can do a user study on the push notification models.

**Comment by lintool** [comment]
Guidelines finalized. Closing issue.
