### ISSUE TITLE
Active client ids

### ISSUE THREAD

**Issue by KaranSabhnani** [trecrts/trecrts.github.io#9]
As there is a cap on the number of active client ids, what will happen if we try to register more than 3? Will the broker discard one of the previous ones and consider the most recent 3 as active or won't allow us to register more than 3?

**Comment by aroegies** [comment]
Currently it'll keep allowing them. When we go official then it will be limited. 
On Jul 21, 2016 7:10 PM, KaranSabhnani notifications@github.com wrote:As there is a cap on the number of active client ids, what will happen if we try to register more than 3? Will the broker discard one of the previous ones and consider the most recent 3 as active or won't allow us to register more than 3?

**Comment by KaranSabhnani** [comment]
Can you please add some more clarity on the transition, like once the official evaluation period starts, will the broker discard all the previous registrations and accept up to 3 new ones? Or continue with some of the previously registered ones (if yes, which ones). I am asking because I plan to start my runs early.

**Comment by aroegies** [comment]
You will be granted three new ids.
On Jul 21, 2016 7:39 PM, KaranSabhnani notifications@github.com wrote:Can you please add some more clarity on the transition, like once the official evaluation period starts, will the broker discard all the previous registrations and accept up to 3 new ones? Or continue with some of the previously registered ones (if yes, which ones). I am asking because I plan to start my runs early.

**Comment by KaranSabhnani** [comment]
and previous client ids will stop working, thus we cannot start our runs early, right?

**Comment by aroegies** [comment]
You can make use of whatever information you gathered beforehand but we'll likely restart the server and so clientids may not be transferable. 
The exact details are still pending. 
On Jul 21, 2016 7:39 PM, KaranSabhnani notifications@github.com wrote:Can you please add some more clarity on the transition, like once the official evaluation period starts, will the broker discard all the previous registrations and accept up to 3 new ones? Or continue with some of the previously registered ones (if yes, which ones). I am asking because I plan to start my runs early.

**Comment by KaranSabhnani** [comment]
okay, thanks.

**Comment by aroegies** [comment]
It wont allow you to register more than 3.
On 7/21/2016 1:10:46 PM, KaranSabhnani notifications@github.com wrote:
As there is a cap on the number of active client ids, what will happen if we try to register more than 3? Will the broker discard one of the previous ones and consider the most recent 3 as active or won't allow us to register more than 3?

**Comment by lintool** [comment]
Closing issue. TREC 2016 over! Reshuffling deck for TREC 2017.
